import * as _3 from "./api/http";
import * as _4 from "./protobuf/any";
import * as _5 from "./protobuf/descriptor";
import * as _6 from "./protobuf/duration";
import * as _7 from "./protobuf/empty";
import * as _8 from "./protobuf/timestamp";
export declare namespace google {
    const api: {
        Http: {
            typeUrl: string;
            encode(message: _3.Http, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _3.Http;
            fromPartial(object: Partial<_3.Http>): _3.Http;
            fromAmino(object: HttpAmino): _3.Http;
            toAmino(message: _3.Http): HttpAmino;
            fromAminoMsg(object: HttpAminoMsg): _3.Http;
            fromProtoMsg(message: HttpProtoMsg): _3.Http;
            toProto(message: _3.Http): Uint8Array;
            toProtoMsg(message: _3.Http): HttpProtoMsg;
        };
        HttpRule: {
            typeUrl: string;
            encode(message: _3.HttpRule, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _3.HttpRule;
            fromPartial(object: Partial<_3.HttpRule>): _3.HttpRule;
            fromAmino(object: HttpRuleAmino): _3.HttpRule;
            toAmino(message: _3.HttpRule): HttpRuleAmino;
            fromAminoMsg(object: HttpRuleAminoMsg): _3.HttpRule;
            fromProtoMsg(message: HttpRuleProtoMsg): _3.HttpRule;
            toProto(message: _3.HttpRule): Uint8Array;
            toProtoMsg(message: _3.HttpRule): HttpRuleProtoMsg;
        };
        CustomHttpPattern: {
            typeUrl: string;
            encode(message: _3.CustomHttpPattern, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _3.CustomHttpPattern;
            fromPartial(object: Partial<_3.CustomHttpPattern>): _3.CustomHttpPattern;
            fromAmino(object: CustomHttpPatternAmino): _3.CustomHttpPattern;
            toAmino(message: _3.CustomHttpPattern): CustomHttpPatternAmino;
            fromAminoMsg(object: CustomHttpPatternAminoMsg): _3.CustomHttpPattern;
            fromProtoMsg(message: CustomHttpPatternProtoMsg): _3.CustomHttpPattern;
            toProto(message: _3.CustomHttpPattern): Uint8Array;
            toProtoMsg(message: _3.CustomHttpPattern): CustomHttpPatternProtoMsg;
        };
    };
    const protobuf: {
        Timestamp: {
            typeUrl: string;
            encode(message: _8.Timestamp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _8.Timestamp;
            fromPartial(object: Partial<_8.Timestamp>): _8.Timestamp;
            fromAmino(object: TimestampAmino): _8.Timestamp;
            toAmino(message: _8.Timestamp): TimestampAmino;
            fromAminoMsg(object: TimestampAminoMsg): _8.Timestamp;
            fromProtoMsg(message: TimestampProtoMsg): _8.Timestamp;
            toProto(message: _8.Timestamp): Uint8Array;
            toProtoMsg(message: _8.Timestamp): TimestampProtoMsg;
        };
        Empty: {
            typeUrl: string;
            encode(_: _7.Empty, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _7.Empty;
            fromPartial(_: Partial<_7.Empty>): _7.Empty;
            fromAmino(_: EmptyAmino): _7.Empty;
            toAmino(_: _7.Empty): EmptyAmino;
            fromAminoMsg(object: EmptyAminoMsg): _7.Empty;
            fromProtoMsg(message: EmptyProtoMsg): _7.Empty;
            toProto(message: _7.Empty): Uint8Array;
            toProtoMsg(message: _7.Empty): EmptyProtoMsg;
        };
        Duration: {
            typeUrl: string;
            encode(message: _6.Duration, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _6.Duration;
            fromPartial(object: Partial<_6.Duration>): _6.Duration;
            fromAmino(object: DurationAmino): _6.Duration;
            toAmino(message: _6.Duration): DurationAmino;
            fromAminoMsg(object: DurationAminoMsg): _6.Duration;
            fromProtoMsg(message: DurationProtoMsg): _6.Duration;
            toProto(message: _6.Duration): Uint8Array;
            toProtoMsg(message: _6.Duration): DurationProtoMsg;
        };
        fieldDescriptorProto_TypeFromJSON(object: any): _5.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _5.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _5.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _5.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _5.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _5.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _5.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _5.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _5.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _5.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _5.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _5.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _5.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _5.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _5.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _5.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _5.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _5.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _5.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _5.FieldOptions_CType;
        FieldOptions_JSType: typeof _5.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _5.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _5.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _5.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            encode(message: _5.FileDescriptorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _5.FileDescriptorSet;
            fromPartial(object: Partial<_5.FileDescriptorSet>): _5.FileDescriptorSet;
            fromAmino(object: FileDescriptorSetAmino): _5.FileDescriptorSet;
            toAmino(message: _5.FileDescriptorSet): FileDescriptorSetAmino;
            fromAminoMsg(object: FileDescriptorSetAminoMsg): _5.FileDescriptorSet;
            fromProtoMsg(message: FileDescriptorSetProtoMsg): _5.FileDescriptorSet;
            toProto(message: _5.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _5.FileDescriptorSet): FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            encode(message: _5.FileDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _5.FileDescriptorProto;
            fromPartial(object: Partial<_5.FileDescriptorProto>): _5.FileDescriptorProto;
            fromAmino(object: FileDescriptorProtoAmino): _5.FileDescriptorProto;
            toAmino(message: _5.FileDescriptorProto): FileDescriptorProtoAmino;
            fromAminoMsg(object: FileDescriptorProtoAminoMsg): _5.FileDescriptorProto;
            fromProtoMsg(message: FileDescriptorProtoProtoMsg): _5.FileDescriptorProto;
            toProto(message: _5.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _5.FileDescriptorProto): FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            encode(message: _5.DescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _5.DescriptorProto;
            fromPartial(object: Partial<_5.DescriptorProto>): _5.DescriptorProto;
            fromAmino(object: DescriptorProtoAmino): _5.DescriptorProto;
            toAmino(message: _5.DescriptorProto): DescriptorProtoAmino;
            fromAminoMsg(object: DescriptorProtoAminoMsg): _5.DescriptorProto;
            fromProtoMsg(message: DescriptorProtoProtoMsg): _5.DescriptorProto;
            toProto(message: _5.DescriptorProto): Uint8Array;
            toProtoMsg(message: _5.DescriptorProto): DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            encode(message: _5.DescriptorProto_ExtensionRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _5.DescriptorProto_ExtensionRange;
            fromPartial(object: Partial<_5.DescriptorProto_ExtensionRange>): _5.DescriptorProto_ExtensionRange;
            fromAmino(object: DescriptorProto_ExtensionRangeAmino): _5.DescriptorProto_ExtensionRange;
            toAmino(message: _5.DescriptorProto_ExtensionRange): DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: DescriptorProto_ExtensionRangeAminoMsg): _5.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: DescriptorProto_ExtensionRangeProtoMsg): _5.DescriptorProto_ExtensionRange;
            toProto(message: _5.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _5.DescriptorProto_ExtensionRange): DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            encode(message: _5.DescriptorProto_ReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _5.DescriptorProto_ReservedRange;
            fromPartial(object: Partial<_5.DescriptorProto_ReservedRange>): _5.DescriptorProto_ReservedRange;
            fromAmino(object: DescriptorProto_ReservedRangeAmino): _5.DescriptorProto_ReservedRange;
            toAmino(message: _5.DescriptorProto_ReservedRange): DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: DescriptorProto_ReservedRangeAminoMsg): _5.DescriptorProto_ReservedRange;
            fromProtoMsg(message: DescriptorProto_ReservedRangeProtoMsg): _5.DescriptorProto_ReservedRange;
            toProto(message: _5.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _5.DescriptorProto_ReservedRange): DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            encode(message: _5.ExtensionRangeOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _5.ExtensionRangeOptions;
            fromPartial(object: Partial<_5.ExtensionRangeOptions>): _5.ExtensionRangeOptions;
            fromAmino(object: ExtensionRangeOptionsAmino): _5.ExtensionRangeOptions;
            toAmino(message: _5.ExtensionRangeOptions): ExtensionRangeOptionsAmino;
            fromAminoMsg(object: ExtensionRangeOptionsAminoMsg): _5.ExtensionRangeOptions;
            fromProtoMsg(message: ExtensionRangeOptionsProtoMsg): _5.ExtensionRangeOptions;
            toProto(message: _5.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _5.ExtensionRangeOptions): ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            encode(message: _5.FieldDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _5.FieldDescriptorProto;
            fromPartial(object: Partial<_5.FieldDescriptorProto>): _5.FieldDescriptorProto;
            fromAmino(object: FieldDescriptorProtoAmino): _5.FieldDescriptorProto;
            toAmino(message: _5.FieldDescriptorProto): FieldDescriptorProtoAmino;
            fromAminoMsg(object: FieldDescriptorProtoAminoMsg): _5.FieldDescriptorProto;
            fromProtoMsg(message: FieldDescriptorProtoProtoMsg): _5.FieldDescriptorProto;
            toProto(message: _5.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _5.FieldDescriptorProto): FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            encode(message: _5.OneofDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _5.OneofDescriptorProto;
            fromPartial(object: Partial<_5.OneofDescriptorProto>): _5.OneofDescriptorProto;
            fromAmino(object: OneofDescriptorProtoAmino): _5.OneofDescriptorProto;
            toAmino(message: _5.OneofDescriptorProto): OneofDescriptorProtoAmino;
            fromAminoMsg(object: OneofDescriptorProtoAminoMsg): _5.OneofDescriptorProto;
            fromProtoMsg(message: OneofDescriptorProtoProtoMsg): _5.OneofDescriptorProto;
            toProto(message: _5.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _5.OneofDescriptorProto): OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            encode(message: _5.EnumDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _5.EnumDescriptorProto;
            fromPartial(object: Partial<_5.EnumDescriptorProto>): _5.EnumDescriptorProto;
            fromAmino(object: EnumDescriptorProtoAmino): _5.EnumDescriptorProto;
            toAmino(message: _5.EnumDescriptorProto): EnumDescriptorProtoAmino;
            fromAminoMsg(object: EnumDescriptorProtoAminoMsg): _5.EnumDescriptorProto;
            fromProtoMsg(message: EnumDescriptorProtoProtoMsg): _5.EnumDescriptorProto;
            toProto(message: _5.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _5.EnumDescriptorProto): EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            encode(message: _5.EnumDescriptorProto_EnumReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _5.EnumDescriptorProto_EnumReservedRange;
            fromPartial(object: Partial<_5.EnumDescriptorProto_EnumReservedRange>): _5.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: EnumDescriptorProto_EnumReservedRangeAmino): _5.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _5.EnumDescriptorProto_EnumReservedRange): EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: EnumDescriptorProto_EnumReservedRangeAminoMsg): _5.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: EnumDescriptorProto_EnumReservedRangeProtoMsg): _5.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _5.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _5.EnumDescriptorProto_EnumReservedRange): EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            encode(message: _5.EnumValueDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _5.EnumValueDescriptorProto;
            fromPartial(object: Partial<_5.EnumValueDescriptorProto>): _5.EnumValueDescriptorProto;
            fromAmino(object: EnumValueDescriptorProtoAmino): _5.EnumValueDescriptorProto;
            toAmino(message: _5.EnumValueDescriptorProto): EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: EnumValueDescriptorProtoAminoMsg): _5.EnumValueDescriptorProto;
            fromProtoMsg(message: EnumValueDescriptorProtoProtoMsg): _5.EnumValueDescriptorProto;
            toProto(message: _5.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _5.EnumValueDescriptorProto): EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            encode(message: _5.ServiceDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _5.ServiceDescriptorProto;
            fromPartial(object: Partial<_5.ServiceDescriptorProto>): _5.ServiceDescriptorProto;
            fromAmino(object: ServiceDescriptorProtoAmino): _5.ServiceDescriptorProto;
            toAmino(message: _5.ServiceDescriptorProto): ServiceDescriptorProtoAmino;
            fromAminoMsg(object: ServiceDescriptorProtoAminoMsg): _5.ServiceDescriptorProto;
            fromProtoMsg(message: ServiceDescriptorProtoProtoMsg): _5.ServiceDescriptorProto;
            toProto(message: _5.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _5.ServiceDescriptorProto): ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            encode(message: _5.MethodDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _5.MethodDescriptorProto;
            fromPartial(object: Partial<_5.MethodDescriptorProto>): _5.MethodDescriptorProto;
            fromAmino(object: MethodDescriptorProtoAmino): _5.MethodDescriptorProto;
            toAmino(message: _5.MethodDescriptorProto): MethodDescriptorProtoAmino;
            fromAminoMsg(object: MethodDescriptorProtoAminoMsg): _5.MethodDescriptorProto;
            fromProtoMsg(message: MethodDescriptorProtoProtoMsg): _5.MethodDescriptorProto;
            toProto(message: _5.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _5.MethodDescriptorProto): MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            encode(message: _5.FileOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _5.FileOptions;
            fromPartial(object: Partial<_5.FileOptions>): _5.FileOptions;
            fromAmino(object: FileOptionsAmino): _5.FileOptions;
            toAmino(message: _5.FileOptions): FileOptionsAmino;
            fromAminoMsg(object: FileOptionsAminoMsg): _5.FileOptions;
            fromProtoMsg(message: FileOptionsProtoMsg): _5.FileOptions;
            toProto(message: _5.FileOptions): Uint8Array;
            toProtoMsg(message: _5.FileOptions): FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            encode(message: _5.MessageOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _5.MessageOptions;
            fromPartial(object: Partial<_5.MessageOptions>): _5.MessageOptions;
            fromAmino(object: MessageOptionsAmino): _5.MessageOptions;
            toAmino(message: _5.MessageOptions): MessageOptionsAmino;
            fromAminoMsg(object: MessageOptionsAminoMsg): _5.MessageOptions;
            fromProtoMsg(message: MessageOptionsProtoMsg): _5.MessageOptions;
            toProto(message: _5.MessageOptions): Uint8Array;
            toProtoMsg(message: _5.MessageOptions): MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            encode(message: _5.FieldOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _5.FieldOptions;
            fromPartial(object: Partial<_5.FieldOptions>): _5.FieldOptions;
            fromAmino(object: FieldOptionsAmino): _5.FieldOptions;
            toAmino(message: _5.FieldOptions): FieldOptionsAmino;
            fromAminoMsg(object: FieldOptionsAminoMsg): _5.FieldOptions;
            fromProtoMsg(message: FieldOptionsProtoMsg): _5.FieldOptions;
            toProto(message: _5.FieldOptions): Uint8Array;
            toProtoMsg(message: _5.FieldOptions): FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            encode(message: _5.OneofOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _5.OneofOptions;
            fromPartial(object: Partial<_5.OneofOptions>): _5.OneofOptions;
            fromAmino(object: OneofOptionsAmino): _5.OneofOptions;
            toAmino(message: _5.OneofOptions): OneofOptionsAmino;
            fromAminoMsg(object: OneofOptionsAminoMsg): _5.OneofOptions;
            fromProtoMsg(message: OneofOptionsProtoMsg): _5.OneofOptions;
            toProto(message: _5.OneofOptions): Uint8Array;
            toProtoMsg(message: _5.OneofOptions): OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            encode(message: _5.EnumOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _5.EnumOptions;
            fromPartial(object: Partial<_5.EnumOptions>): _5.EnumOptions;
            fromAmino(object: EnumOptionsAmino): _5.EnumOptions;
            toAmino(message: _5.EnumOptions): EnumOptionsAmino;
            fromAminoMsg(object: EnumOptionsAminoMsg): _5.EnumOptions;
            fromProtoMsg(message: EnumOptionsProtoMsg): _5.EnumOptions;
            toProto(message: _5.EnumOptions): Uint8Array;
            toProtoMsg(message: _5.EnumOptions): EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            encode(message: _5.EnumValueOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _5.EnumValueOptions;
            fromPartial(object: Partial<_5.EnumValueOptions>): _5.EnumValueOptions;
            fromAmino(object: EnumValueOptionsAmino): _5.EnumValueOptions;
            toAmino(message: _5.EnumValueOptions): EnumValueOptionsAmino;
            fromAminoMsg(object: EnumValueOptionsAminoMsg): _5.EnumValueOptions;
            fromProtoMsg(message: EnumValueOptionsProtoMsg): _5.EnumValueOptions;
            toProto(message: _5.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _5.EnumValueOptions): EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            encode(message: _5.ServiceOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _5.ServiceOptions;
            fromPartial(object: Partial<_5.ServiceOptions>): _5.ServiceOptions;
            fromAmino(object: ServiceOptionsAmino): _5.ServiceOptions;
            toAmino(message: _5.ServiceOptions): ServiceOptionsAmino;
            fromAminoMsg(object: ServiceOptionsAminoMsg): _5.ServiceOptions;
            fromProtoMsg(message: ServiceOptionsProtoMsg): _5.ServiceOptions;
            toProto(message: _5.ServiceOptions): Uint8Array;
            toProtoMsg(message: _5.ServiceOptions): ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            encode(message: _5.MethodOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _5.MethodOptions;
            fromPartial(object: Partial<_5.MethodOptions>): _5.MethodOptions;
            fromAmino(object: MethodOptionsAmino): _5.MethodOptions;
            toAmino(message: _5.MethodOptions): MethodOptionsAmino;
            fromAminoMsg(object: MethodOptionsAminoMsg): _5.MethodOptions;
            fromProtoMsg(message: MethodOptionsProtoMsg): _5.MethodOptions;
            toProto(message: _5.MethodOptions): Uint8Array;
            toProtoMsg(message: _5.MethodOptions): MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            encode(message: _5.UninterpretedOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _5.UninterpretedOption;
            fromPartial(object: Partial<_5.UninterpretedOption>): _5.UninterpretedOption;
            fromAmino(object: UninterpretedOptionAmino): _5.UninterpretedOption;
            toAmino(message: _5.UninterpretedOption): UninterpretedOptionAmino;
            fromAminoMsg(object: UninterpretedOptionAminoMsg): _5.UninterpretedOption;
            fromProtoMsg(message: UninterpretedOptionProtoMsg): _5.UninterpretedOption;
            toProto(message: _5.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _5.UninterpretedOption): UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            encode(message: _5.UninterpretedOption_NamePart, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _5.UninterpretedOption_NamePart;
            fromPartial(object: Partial<_5.UninterpretedOption_NamePart>): _5.UninterpretedOption_NamePart;
            fromAmino(object: UninterpretedOption_NamePartAmino): _5.UninterpretedOption_NamePart;
            toAmino(message: _5.UninterpretedOption_NamePart): UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: UninterpretedOption_NamePartAminoMsg): _5.UninterpretedOption_NamePart;
            fromProtoMsg(message: UninterpretedOption_NamePartProtoMsg): _5.UninterpretedOption_NamePart;
            toProto(message: _5.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _5.UninterpretedOption_NamePart): UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            encode(message: _5.SourceCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _5.SourceCodeInfo;
            fromPartial(object: Partial<_5.SourceCodeInfo>): _5.SourceCodeInfo;
            fromAmino(object: SourceCodeInfoAmino): _5.SourceCodeInfo;
            toAmino(message: _5.SourceCodeInfo): SourceCodeInfoAmino;
            fromAminoMsg(object: SourceCodeInfoAminoMsg): _5.SourceCodeInfo;
            fromProtoMsg(message: SourceCodeInfoProtoMsg): _5.SourceCodeInfo;
            toProto(message: _5.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _5.SourceCodeInfo): SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            encode(message: _5.SourceCodeInfo_Location, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _5.SourceCodeInfo_Location;
            fromPartial(object: Partial<_5.SourceCodeInfo_Location>): _5.SourceCodeInfo_Location;
            fromAmino(object: SourceCodeInfo_LocationAmino): _5.SourceCodeInfo_Location;
            toAmino(message: _5.SourceCodeInfo_Location): SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: SourceCodeInfo_LocationAminoMsg): _5.SourceCodeInfo_Location;
            fromProtoMsg(message: SourceCodeInfo_LocationProtoMsg): _5.SourceCodeInfo_Location;
            toProto(message: _5.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _5.SourceCodeInfo_Location): SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            encode(message: _5.GeneratedCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _5.GeneratedCodeInfo;
            fromPartial(object: Partial<_5.GeneratedCodeInfo>): _5.GeneratedCodeInfo;
            fromAmino(object: GeneratedCodeInfoAmino): _5.GeneratedCodeInfo;
            toAmino(message: _5.GeneratedCodeInfo): GeneratedCodeInfoAmino;
            fromAminoMsg(object: GeneratedCodeInfoAminoMsg): _5.GeneratedCodeInfo;
            fromProtoMsg(message: GeneratedCodeInfoProtoMsg): _5.GeneratedCodeInfo;
            toProto(message: _5.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _5.GeneratedCodeInfo): GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            encode(message: _5.GeneratedCodeInfo_Annotation, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _5.GeneratedCodeInfo_Annotation;
            fromPartial(object: Partial<_5.GeneratedCodeInfo_Annotation>): _5.GeneratedCodeInfo_Annotation;
            fromAmino(object: GeneratedCodeInfo_AnnotationAmino): _5.GeneratedCodeInfo_Annotation;
            toAmino(message: _5.GeneratedCodeInfo_Annotation): GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: GeneratedCodeInfo_AnnotationAminoMsg): _5.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: GeneratedCodeInfo_AnnotationProtoMsg): _5.GeneratedCodeInfo_Annotation;
            toProto(message: _5.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _5.GeneratedCodeInfo_Annotation): GeneratedCodeInfo_AnnotationProtoMsg;
        };
        Any: {
            typeUrl: string;
            encode(message: _4.Any, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _4.Any;
            fromPartial(object: Partial<_4.Any>): _4.Any;
            fromAmino(object: AnyAmino): _4.Any;
            toAmino(message: _4.Any): AnyAmino;
            fromAminoMsg(object: AnyAminoMsg): _4.Any;
            fromProtoMsg(message: AnyProtoMsg): _4.Any;
            toProto(message: _4.Any): Uint8Array;
            toProtoMsg(message: _4.Any): AnyProtoMsg;
        };
    };
}
